### PR TITLE
examples -- EvenOrOdd and Factorial -- add

### PR DESCRIPTION
**Pull request by da8**
Hi Jeremy, 

I added an example for "[ADD EXAMPLE] Even or odd #17" based on the code you published  at https://rosettacode.org/wiki/Even_or_odd#Processing. 

Would you mind adding it to the code base of the examples?

Best regards,

Dawit

### CODE REVIEW

**Comment by da8** [comment]
I added an example for the issue [ADD EXAMPLE] Factorial #18 and corrected the processing version in EvenOrOdd.pde to Processing 3.5.4.

**Comment by da8** [comment]
I added an example for the issue [ADD EXAMPLE] Factorial #18 and corrected the processing version in EvenOrOdd.pde to Processing 3.5.4.

**Comment by jeremydouglass** [comment]
Hi Dawit -- thank you so much, and welcome! I will take a look right now.

One minor point re: "based on the code you published" -- that code contributed to the wiki is not by me -- from the wiki History, it looks like it was contributed 5 Sept 2017 by "CerealKiller".

> 13:05, 5 September 2017‎ CerealKiller (Talk | contribs)‎ . . (65,539 bytes) (+141)‎ . . (Processing code added)
https://rosettacode.org/mw/index.php?title=Even_or_odd&type=revision&diff=252297&oldid=252028

Under the RosettaWiki contributor terms that is republish-able by this project, but we'll also add a credit.

**Comment by jeremydouglass** [comment]
Closes #17 and #18

**Pull request merged**
