### PR TITLE
Java examples ported to Python mode

### PR DESCRIPTION
**Pull request by villares**
Work in progress...

Jeremy, I wonder how to create an empty `docs` folder for the rename example.

### CODE REVIEW

**Comment by villares** [comment]
I think I'm done!

**Comment by jeremydouglass** [comment]
> I wonder how to create an empty docs folder for the rename example.

There is no such thing as an empty folder in git. I often use the convention of creating an empty .gitkeep file as a placeholder to preserve the empty folder.

**Comment by villares** [comment]
Cool! .gitkeep added!

**Comment by jeremydouglass** [comment]
Screen Shot 2020-04-04 at 12 21 05 PM

Thank so much for all this great work, @villares . Just so you know, this is what an interactive rebase looks like (I'm using SourceTree rather than the command line in this example).

1. I check out your pr branch.
2. interactive rebase onto master (right-click on master and select interactive rebase, in sourcetree)
3. drag your 15 commits into five clusters, mark all the later ones in each cluster "squash with previous" to turn them into five groups
4. edit the five commit messages if needed so the first line for each is simple ("add" not "one last comment tweak")
5. commit

**Comment by jeremydouglass** [comment]
Great, all merged. 

AND: for rebasing, do as I say, not as I do ;)

The rebase commit ran into some conflicts on your Comments.pyde changes and then SourceTree offset the commit message chain (mismatching messages to commits). I didn't notice until after I pushed, so I had to force-push a fix to master.

Please force-delete your Other-Python-Ports branch!

**Pull request merged**
