### PR TITLE
Update issue templates -- add Python mode

### PR DESCRIPTION
**Pull request by jeremydouglass**
based on work by @villares

### CODE REVIEW

**Comment by villares** [comment]
Hi!

There are some issues on this you might want to consider:
there is a category URL already at https://rosettacode.org/wiki/Category:Processing_Python (not ProcessingPython) I think we should see how to make it a sub-category really...
But I'm afraid the unimplemented search only works on categories... to be seen.

**Comment by jeremydouglass** [comment]
If you are excited about contributing to the wiki, then I think we should do it the way that you like best. Would you prefer it to be a subcategory, or a separate category, and what name would you like best?

Anything on the wiki we can change, and we'll make this issue template and CONTRIBUTING.md match the wiki.

**Comment by villares** [comment]
I find the wiki infrastructure quite confusing... I'll have to take the time to study it
I confess I'm more excited about porting examples...

**Comment by jeremydouglass** [comment]
Okay, for now let's just push forward with what we have -- and not lose energy or enthusiasm. We can fix it up later!

**Comment by villares** [comment]
So, I think the wiki thing is really hard... I will suggest this:
```
Find Processing task code on the wiki with no sketch in this repo:
    https://rosettacode.org/wiki/Category:Processing
You may also check if there are both Python and Java mode examples for the task, and if you are interested in first contributing new Processing task code to the wiki, check:
    https://rosettacode.org/wiki/Reports:Tasks_not_implemented_in_Processing
```
And then count only on the category automated report for the time being.
I would even remove the Processing_Python category if I could.

**Comment by jeremydouglass** [comment]
Okay. I think that I have figured this out. A good model on the wiki is BASIC -- it is both a language and a family of sublanguages (which are not libraries) -- each sublanguage has its own category page and examples list, is listed under the BASIC category, and its entries can be nested under the top level heading on an individual page.

https://rosettacode.org/wiki/100_doors#BASIC

This is much better than using the libraries or non-header subsection approach, because then nobody can find anything except by clicking through every individual page -- doesn't work with hundreds or thousands of pages.

https://rosettacode.org/wiki/Category:Processing
https://rosettacode.org/wiki/Category:Processing_Python_mode

**Comment by jeremydouglass** [comment]
Great, I went through the Rosetta Code wiki and updated all Python mode examples so far as subcategories of Processing on each example page -- and they are indexed! The issues template now points to them correctly, so I'll update for new issues. Will also need to update CONTRIBUTING.md soon to match.

**Pull request merged**
