### PR TITLE
Draw a clock work

### PR DESCRIPTION
**Pull request by villares**
- Completed a comment in the Java mode version
- Created the Python mode version issue #49

### CODE REVIEW

**Comment by jeremydouglass** [comment]
The changes look good!

Given that the only changes are in the last three commits, could you rebase / force-push your PR so that it is just those last three commits? Or just force-push the PR with one or two commit that is just the pde and pyde file in a new commit?

**Comment by villares** [comment]
I can if you give me detailed instructions on how to do it, I'm completely clueless
Those ugly commits are due to my inaptitude with bringing my fork in sync... I considered removing my fork and starting over...

**Comment by jeremydouglass** [comment]
Sure! -- what are you using -- git command line, SourceTree, GitHub Desktop...?

**Comment by villares** [comment]
GitHub Desktop and git command line :-S

**Comment by jeremydouglass** [comment]
Sorry, I've been meaning to write this up: it is a lot of steps to rebase your PR and then force-push it so that the commits don't come wrapped in all the old stuff. I'm going to just try it on my end, and then we can simplify this a lot going forward.

**Comment by jeremydouglass** [comment]
Closed by feef9ba and d3c1cc6

**Comment by jeremydouglass** [comment]
Here is what I suggest: just delete your fork and refork from master. Make sure to save any changes first, of course!

From here on it out it should be much easier to just merge your pulls.

**Comment by villares** [comment]
Cool!
Then you teach me how to proceed next time :)

**Comment by villares** [comment]
Wow! I thought I would have to re-create my branches and submit new pull requests, now I see you have done all the work :/   Sorry for the mess.

So I have removed and re-added my fork.

At some point, if you could please advise on what to do when your repo inevitably goes faster and out of sync with my fork... 

Cheers!

**Comment by jeremydouglass** [comment]
Cheers! And thanks for all the great commits!

If there is no massive refactor in your history then we should be good from here on out.

Here is one way to keep things clean:

1. Leave "master" on your fork for pulling updates from upstream. Don't commit to master! Just pull it.

2. If you want to do something, create a branch. For example, if you want to make a sketch called "RandomColors", make a branch off a version commit on master (e.g. v0.11) and add some commits there. Make as many branches as you want -- you can have dozens or hundreds of branches if you have drafts just hanging out.
3. When one is done, make a pull request from that branch, "RandomColors". It will always be clean. If I need to do any fiddling, I can do it right there in your PR branch -- which means I can merge from your branch.

But What if you commit (one or more times) things that were meant for "RandomColors" into another branch instead -- or commit something to master -- on accident. Then:

1. Clean up all other work first.
2. Checkout the right branch it should have gone to: "RandomColors"
3. Cherry-pick the oops commit(s) into the right branch
4. Check out the dirty branch (master or 
5. Reset (hard) that branch to the previous commit to delete the bad commit.

**Pull request closed without merging**
