### PR TITLE
Mouse position

### PR DESCRIPTION
**Pull request by villares**
I added this to the wiki. I find this task being easy to be one of the main Processing strengths.

### CODE REVIEW

**Comment by villares** [comment]
sorry I guess I made a forking mess again. I will remove and start again.

**Comment by jeremydouglass** [comment]
What I sometimes do is start a branch (not a pull request), and then when I am ready to pull I rebase first before pulling. That lets me put my changes on top of current master and squash together my little fixes. But there are lots of different ways of working.

**Comment by villares** [comment]
Sounds marvelous, but I'm rebase clueless still... I will learn this some day, I hope...

**Comment by jeremydouglass** [comment]
Eventually added in 66e28cfbf42372b8e1765c4463833539fe6371c9

**Pull request closed without merging**
