### PR TITLE
Julia set

### PR DESCRIPTION
**Pull request by villares**
Processing Java & Processing Python examples from the wiki
Possibly solves #24

### CODE REVIEW

**Comment by villares** [comment]
See if you find the last commit (making the Python mode more like the Java mode) necessary...

**Comment by jeremydouglass** [comment]
Great! Thank you so much.

Some very small things to lint -- like the title in the .pde header, and globals-setup-draw normal order -- so I just tacked on a commit while merging rather than doing a review.

These look really good. I've been thinking about possibly adding screenshots to all the relevant sketches -- but there are some potential downsides.... (see #61 )

**Comment by villares** [comment]
Yeah, I hated the globals after setup order... it was from the Java mode version on the wiki so I preserved it.

**Comment by jeremydouglass** [comment]
I think we are both agreed -- let's fix the wiki instead when we see that again. That's just not idiomatic Processing (or good Java, really). It's a wiki -- we can make it better.

**Pull request merged**
