### PR TITLE
Game of Life

### PR DESCRIPTION
**Pull request by villares**
The world's best known Cellular Automata, how could it be missing in Processing at Rosetta Code?

### CODE REVIEW

**Comment by jeremydouglass** [comment]
Looks really great! I'm proposing (pushing for your inspection) two minor changes -- 

1. one to make the speed more inspectable
2. another to make the mouse "draw" while pressed / dragging, and pause the animation while drawing is taking place. It uses a lock field to prevent cells from fast-cycling on and off.

Let me know if you like them or would rather drop them -- either is fine.

One note about the update to the old mouse loop code -- we don't have to loop over cells and check them for a collision, we can just compute the current cell directly from mouseX/mouseY.

**Comment by villares** [comment]
Great proposals! Much better!
Please check if Python mode reflects them correctly.

**Comment by jeremydouglass** [comment]
Merged -- thanks so much!

At this point, are the examples ahead of the wiki?

**Comment by villares** [comment]
I have updated the Rosetta Code wiki now :)

**Pull request merged**
